version: 2
jobs:
  test:
    docker:
      - image: circleci/node:jessie-browsers
    steps:
      - checkout
      - run:
          name: Make Report Directory
          command: mkdir report

      - run:
          name: Install Node Modules
          command: npm install
      - run:
          name: Execute ESlint Check
          command: npm run eslint-check
      - run:
          name: Test
          command: npm test wdio.conf.js
      - store_test_results:
          path: report
workflows:
  version: 2
  test:
    jobs:
      - test
